# AndroidOnly: WP-218 Reject incomplete or broadened generated lock admission.
import importlib.util
from pathlib import Path
import unittest

path = Path(__file__).with_name("verify_content_locks.py")
spec = importlib.util.spec_from_file_location("wp218_content_locks", path)
reader = importlib.util.module_from_spec(spec)
spec.loader.exec_module(reader)


class ContentLockTest(unittest.TestCase):
    def state(self):
        before = {name: {"example:existing:1.0"} for name in reader.CONFIGURATIONS}
        before["kotlinInternalAbiValidation"] = {"example:existing:1.0"}
        before["annotationProcessor"] = set()
        admitted = {name: set(reader.ADDITIONS) for name in reader.CONFIGURATIONS}
        after = {name: values | admitted.get(name, set()) for name, values in before.items()}
        return before, after, admitted

    def test_exact_admitted_additions_preserve_other_configurations(self):
        reader.verify_delta(*self.state())

    def test_missing_regeneration_is_blocked(self):
        before, _, admitted = self.state()
        with self.assertRaises(ValueError):
            reader.verify_delta(before, before, admitted)

    def test_changed_existing_version_is_blocked(self):
        before, after, admitted = self.state()
        after["testRuntimeClasspath"].remove("example:existing:1.0")
        after["testRuntimeClasspath"].add("example:existing:2.0")
        with self.assertRaises(ValueError):
            reader.verify_delta(before, after, admitted)

    def test_extra_artifact_is_blocked(self):
        before, after, admitted = self.state()
        after["testRuntimeClasspath"].add("example:unadmitted:1.0")
        with self.assertRaises(ValueError):
            reader.verify_delta(before, after, admitted)

    def test_out_of_scope_configuration_change_is_blocked(self):
        before, after, admitted = self.state()
        after["kotlinInternalAbiValidation"].update(reader.ADDITIONS)
        with self.assertRaises(ValueError):
            reader.verify_delta(before, after, admitted)

    def test_missing_or_broadened_admission_is_blocked(self):
        for broaden in (False, True):
            before, after, admitted = self.state()
            if broaden:
                admitted["kotlinInternalAbiValidation"] = set(reader.ADDITIONS)
            else:
                del admitted["testRuntimeClasspath"]
            with self.assertRaises(ValueError):
                reader.verify_delta(before, after, admitted)

    def test_empty_and_crlf_lock_records_are_preserved(self):
        self.assertEqual({"testRuntimeClasspath": {"example:existing:1.0"}, "annotationProcessor": set()},
            reader.parse_lock("# Generated by Gradle\r\nexample:existing:1.0=testRuntimeClasspath\r\n"
                "empty=annotationProcessor\r\n"))

    def test_malformed_zero_and_duplicate_records_are_blocked(self):
        for text in ("", "# Header only", "invalid", "example:existing:1.0=", "example:existing:1.0=debug,debug",
            "example:existing:1.0=debug\nexample:existing:1.0=release", "example::1.0=debug",
            "example:existing:=debug", "example:existing:1.0=debug\nempty=debug",
            "empty=debug\nexample:existing:1.0=debug"):
            with self.assertRaises(ValueError):
                reader.parse_lock(text)
