// Generated from docs/android/test-cases.json at frozen source db14559b39d32322b06477c6ae676112f583db50.
// AndroidOnly: WP-309 Verifies the complete owned original-case inventory stays explicit.
package com.meshcoreone.android.feature.chats.actions

import kotlin.test.assertEquals
import org.junit.Test

class OriginalCaseInventoryTest {
    @Test
    fun `all owned original cases are mapped exactly once`() {
        assertEquals(102, ORIGINAL_CASES.size)
        assertEquals(ORIGINAL_CASES.size, ORIGINAL_CASES.toSet().size)
    }
}

private val ORIGINAL_CASES = listOf(
    "MessagePathFormatterTests::pathLength 0 with no pathNodes returns Flood (zero-hop flood)()",
    "MessagePathFormatterTests::pathLength 0xFF returns Direct()",
    "MessagePathFormatterTests::pathLength 1 with 0xFF destination marker returns Direct()",
    "MessagePathFormatterTests::Single node path formats correctly()",
    "MessagePathFormatterTests::Three node path formats with commas()",
    "MessagePathFormatterTests::Zero-byte node formats correctly()",
    "MessagePathFormatterTests::Missing pathNodes on flood-routed returns Flood()",
    "MessagePathFormatterTests::pathLength doesn't match pathNodes count - shows actual nodes()",
    "MessagePathFormatterTests::Mode-1 path chunks bytes into 2-byte hops()",
    "MessagePathFormatterTests::Mode-2 path chunks bytes into 3-byte hops()",
    "MessagePathFormatterTests::Four-node path is shown in full (at the cap)()",
    "MessagePathFormatterTests::Path longer than four nodes collapses the middle to a tight ellipsis()",
    "MessagePathViewModelTests::sender name uses full key prefix match()",
    "MessagePathViewModelTests::sender resolution marks short prefix match as fallback()",
    "MessagePathViewModelTests::sender resolution marks unique short prefix match as exact()",
    "MessagePathViewModelTests::sender resolution marks full prefix match as exact()",
    "MessagePathViewModelTests::sender name returns channel sender node name for channel messages()",
    "MessagePathViewModelTests::sender name returns unknown when no key prefix match()",
    "MessagePathViewModelTests::sender resolution uses local device name for outgoing channel messages()",
    "MessagePathViewModelTests::sender resolution ignores local device name for incoming channel messages()",
    "MessagePathViewModelTests::senderNodeID returns hex of first prefix byte()",
    "MessagePathViewModelTests::senderNodeID returns nil when no key prefix()",
    "MessagePathViewModelTests::senderNodeID returns nil for empty key prefix()",
    "MessagePathViewModelTests::senderNodeID formats leading zero correctly()",
    "MessagePathViewModelTests::locatedSender matches DM by key prefix()",
    "MessagePathViewModelTests::locatedSender returns nil for DM prefix match without location()",
    "MessagePathViewModelTests::locatedSender matches unique channel sender name with location()",
    "MessagePathViewModelTests::locatedSender returns nil for unique channel name without location()",
    "MessagePathViewModelTests::locatedSender returns nil when two contacts share the channel sender name()",
    "MessagePathViewModelTests::locatedSender returns nil when no contact matches the channel sender name()",
    "MessagePathViewModelTests::locatedSender prefers key prefix over channel name when prefix matches()",
    "MessagePathViewModelTests::locatedSender matches channel sender name case-insensitively()",
    "MessagePathViewModelTests::locatedSender includes a unique blocked contact()",
    "MessagePathViewModelTests::repeaterName returns unknown when no contacts match()",
    "MessagePathViewModelTests::loadContacts with nil dataStore sets isLoading false and clears data()",
    "ChatViewModelReactionIndexingTests::DM scope matches a queued pending reaction, persists it scoped to the contact, and updates the summary()",
    "ChatViewModelReactionIndexingTests::Channel scope matches a queued pending reaction, persists it scoped to the channel, and updates the summary()",
    "ChatViewModelReactionIndexingTests::Re-queued duplicate reaction is dropped by the reactionExists guard()",
    "ChatViewModelReactionIndexingTests::Channel scope skips outgoing messages when the local node name is unknown()",
    "MessagePathArrivalTests::incoming with 0 extras is one first arrival()",
    "MessagePathArrivalTests::incoming with 2 extras is canonical then extras in time order()",
    "MessagePathArrivalTests::incoming empty pathNodes with one extra still has a first 0-hop arrival()",
    "MessagePathArrivalTests::outgoing with 2 repeats has no first arrival()",
    "MessagePathArrivalTests::outgoing identical-path echoes stay three arrivals()",
    "MessagePathArrivalTests::outgoing with pathNodes nil still reads hops from the arrival()",
    "MessagePathArrivalTests::incoming 0-hop canonical is not Path Unavailable()",
    "MessagePathDetailSelectionTests::resolvedSelection prefers the current id()",
    "MessagePathDetailSelectionTests::resolvedSelection falls back to first when current vanishes()",
    "MessagePathDetailSelectionTests::resolvedSelection uses first when preferred is nil()",
    "MessagePathDetailSelectionTests::resolvedSelection is nil when arrivals are empty()",
    "MessagePathDetailSelectionTests::canvasModel point ids stay stable across rebuilds()",
    "MessagePathDetailSelectionTests::canvasModel outgoing with located device includes point A at the device coordinate()",
    "MessagePathDetailSelectionTests::canvasModel outgoing line starts at the located device()",
    "MessagePathDetailSelectionTests::canvasModel camera follows the selected arrival()",
    "MessagePathDetailSelectionTests::canvasModel draws only the selected arrival's line and hops()",
    "MessagePathDetailSelectionTests::canvasModel endpoint ids survive selecting another arrival()",
    "MessagePathDetailSelectionTests::canvasModel distance is complete when every path hop is exact and located()",
    "MessagePathDetailSelectionTests::canvasModel distance is incomplete when a hop is unresolved()",
    "MessagePathDetailSelectionTests::canvasModel distance is incomplete when an exact hop has no location()",
    "MessagePathDetailSelectionTests::canvasModel distance is incomplete when a hop is a fallback match()",
    "MessagePathDetailSelectionTests::canvasModel distance stays complete when the same located hop appears twice()",
    "MessagePathDetailSelectionTests::canvasModel hides the path map for a 0-hop arrival with no located endpoint()",
    "MessagePathDetailSelectionTests::canvasModel hides the path map when a hop is unique in contacts but collides with a discovered node()",
    "MessagePathDetailSelectionTests::canvasModel hides the path map when only one hop is placed()",
    "MessagePathDetailSelectionTests::canvasModel shows the path map when two hops are placed and another is skipped()",
    "MessagePathPreviewMapTests::overlay exposes distance and incomplete without hops()",
    "MessagePathPreviewSnapshotTests::width buckets ignore one-point jitter()",
    "MessagePathViewModelPreviewTests::prefetch stores an image and skips a second render of the same key()",
    "MessagePathViewModelPreviewTests::nil render marks failed and retry calls the renderer again()",
    "MessagePathViewModelPreviewTests::prefetch while loading does not render or drop a stored image()",
    "ReactionDetailsSelectionTests::preferred emoji is selected when present()",
    "ReactionDetailsSelectionTests::missing preferred falls back to first()",
    "ReactionDetailsSelectionTests::nil preferred uses first()",
    "ReactionDetailsSelectionTests::empty groups yield nil()",
    "RepeatRowViewTests::unique short prefix is exact()",
    "RepeatRowViewTests::colliding short prefix is fallback()",
    "RepeatRowViewTests::unmatched hash is unresolved()",
    "MessageActionAvailabilityTests::flood-routed with non-empty pathNodes returns true()",
    "MessageActionAvailabilityTests::flood-routed with empty pathNodes returns false()",
    "MessageActionAvailabilityTests::flood-routed with nil pathNodes returns false()",
    "MessageActionAvailabilityTests::direct-routed returns false()",
    "MessageActionAvailabilityTests::outgoing message returns false()",
    "MessageActionAvailabilityTests::channel message with routeType .direct is still flood-routed (channelIndex overrides)()",
    "MessageActionAvailabilityTests::incoming flood with no extras still shows path detail via canViewPath()",
    "MessageActionAvailabilityTests::incoming flood with empty path and one extra still shows path detail()",
    "MessageActionAvailabilityTests::incoming flood with nil path and one extra still shows path detail()",
    "MessageActionAvailabilityTests::outgoing with heard repeats shows path detail()",
    "MessageActionAvailabilityTests::outgoing with no repeats hides path detail()",
    "MessageActionAvailabilityTests::.flood routeType is flood-routed()",
    "MessageActionAvailabilityTests::.tcFlood routeType is flood-routed()",
    "MessageActionAvailabilityTests::.direct routeType is not flood-routed()",
    "MessageActionAvailabilityTests::.tcDirect routeType is not flood-routed()",
    "MessageActionAvailabilityTests::unknown routeType with channelIndex is flood-routed()",
    "MessageActionAvailabilityTests::unknown routeType with pathLength 0xFF is direct-routed()",
    "MessageActionAvailabilityTests::unknown routeType with non-0xFF pathLength is flood-routed()",
    "MessageActionAvailabilityTests::.direct routeType is direct-routed()",
    "MessageActionAvailabilityTests::.tcDirect routeType is direct-routed()",
    "MessageActionAvailabilityTests::channel incoming message with sender name returns true()",
    "MessageActionAvailabilityTests::channel outgoing message returns false()",
    "MessageActionAvailabilityTests::DM incoming message returns false()",
    "MessageActionAvailabilityTests::channel incoming prefix-only message cannot send DM()",
    "MessageActionAvailabilityTests::channel incoming prefix-only message cannot block sender()",
)
