{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent-compose/1.0.2/navigationevent-compose-1.0.2.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent-compose",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14757970"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-compose.aar",
          "url": "navigationevent-compose-android-1.0.2.aar",
          "size": 31310,
          "sha512": "ffd1162a3a3350abe6d49b7af2b17d1f7cea423f84902a8b2e3ad095843322ba28148a91143cbf17e65e23caa138c71d8b8065b179703c869fbf8ac3cd0f4a79",
          "sha256": "6064ee738c2f3c99e1754f6aa380aabb57bf1ba973a4566276a3ecbbd2eaa3d0",
          "sha1": "d1cdadf149ca2fbf6c6312683d432212377d0f16",
          "md5": "cfe62840fea9a20a5810fc5897050f3c"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "LocalView"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-compose.aar",
          "url": "navigationevent-compose-android-1.0.2.aar",
          "size": 31310,
          "sha512": "ffd1162a3a3350abe6d49b7af2b17d1f7cea423f84902a8b2e3ad095843322ba28148a91143cbf17e65e23caa138c71d8b8065b179703c869fbf8ac3cd0f4a79",
          "sha256": "6064ee738c2f3c99e1754f6aa380aabb57bf1ba973a4566276a3ecbbd2eaa3d0",
          "sha1": "d1cdadf149ca2fbf6c6312683d432212377d0f16",
          "md5": "cfe62840fea9a20a5810fc5897050f3c"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-compose-android-1.0.2-sources.jar",
          "url": "navigationevent-compose-android-1.0.2-sources.jar",
          "size": 15354,
          "sha512": "2cb9bc1cb4b4d3ff739ad69e1dea5d7ce252f763364fbe6960bfe5da60c225a8ffc09608d5137b2934eb70dab63fc5e218996fdf24bd6a86d92d2d2447bfeeee",
          "sha256": "e2bfbe6e14a3d6353d18add88eaf9200c163570a0ca7811b51755a13a04f800e",
          "sha1": "1fd8d50e679f55a6881d4ecf7d57b815708d22ec",
          "md5": "1e91e65f4301dcbe8ab0ad493b889bf3"
        },
        {
          "name": "navigationevent-compose-1.0.2-samples-sources.jar",
          "url": "navigationevent-compose-android-1.0.2-samples-sources.jar",
          "size": 5859,
          "sha512": "ade557bee51aab3e41cde6381162fb98e8053ab0a9349fad48367d34bd5cebab5a76cb5081ad0f933e4a3f27ffb56f4ada3f1c5b2563acde1cad98d44d2fc1ac",
          "sha256": "df63ae9684f469f4538795438481b802b394d365566b5af25487e0eef2f4ac6f",
          "sha1": "b7d83bf2bf811c87eec0c4133cf342e08043060e",
          "md5": "3dc3a37e0a809197bcd92e7bf8e9c888"
        }
      ]
    }
  ]
}