{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigationevent",
    "module": "navigationevent-compose",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14757970"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-compose-metadata-1.0.2.jar",
          "url": "navigationevent-compose-1.0.2.jar",
          "size": 11814,
          "sha512": "a41e2e043e735bb7091115853cd129fa158bc0766c8a184189fb14f8dd1f45f1e91acdbdaed30048a92592c06977a68c296ce4374d04babc5148f235d4e29c5b",
          "sha256": "7ac6fd7c9cf2523d5199ec3cecdf7a9870ef9e686cb494dd6aa3a8b90029cb80",
          "sha1": "87ba6eed51d450a36f1ff1963d5ea37784518590",
          "md5": "ed6c658b89cb53e71e3c4ad6ac36cada"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-compose-kotlin-1.0.2-sources.jar",
          "url": "navigationevent-compose-1.0.2-sources.jar",
          "size": 16188,
          "sha512": "b4a81b80a1d359e1ee76bf688676f409096a9a6967e606c180b3d13265e23aee083167d99a09fb5e7d10017ca5c517ce5cdc5e96b033deebac7d6f75d1f3c094",
          "sha256": "c2df938dad25254a5cbeed7dd22139810ea8f9fe3aa24284cef84ef7f5eae80d",
          "sha1": "53b8361c8d0a257e843570fd4abd6bcf2a24d31b",
          "md5": "9af0a3a13fb3f682a09d88206166c915"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-compose-1.0.2-multiplatform-sources.jar",
          "url": "navigationevent-compose-1.0.2-multiplatform-sources.jar",
          "size": 15646,
          "sha512": "fdadab122e36010aa3acc1027378163b4562cf7a3a2d724ef85c13643a3d16b78bd82262bbec0f3d587551d4273ac503b34a4411fc442f55d82ec6c6f30a7dab",
          "sha256": "d4153b45efaf32bee849aeea909eb16cf89a8c213d5ecf5b303401077b3bdd03",
          "sha1": "79c98925911eb54880989565f134035cb0b0d30e",
          "md5": "be5ba18ab3eba2f69e6e3aa91a57e1e2"
        },
        {
          "name": "navigationevent-compose-1.0.2-samples-sources.jar",
          "url": "navigationevent-compose-1.0.2-samples-sources.jar",
          "size": 5859,
          "sha512": "ade557bee51aab3e41cde6381162fb98e8053ab0a9349fad48367d34bd5cebab5a76cb5081ad0f933e4a3f27ffb56f4ada3f1c5b2563acde1cad98d44d2fc1ac",
          "sha256": "df63ae9684f469f4538795438481b802b394d365566b5af25487e0eef2f4ac6f",
          "sha1": "b7d83bf2bf811c87eec0c4133cf342e08043060e",
          "md5": "3dc3a37e0a809197bcd92e7bf8e9c888"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "navigationevent-compose-1.0.2-versionMetadata.json",
          "size": 3569,
          "sha512": "160529378ba021f6714ebe10414beeda50a4ecb2f4948cffd14a2e5f77a827f5cc8e0822d37067764b6d83d394c8abcf8df257af0b143773c80020e3dd9f88bd",
          "sha256": "77bec17a323a50a93cb9368cb3057c076c0257804fdefd8f5d5a45589831ee0f",
          "sha1": "44cd2d740300286ba251e5386c0ffcd12d13ad99",
          "md5": "45ed85594cd73bdd864ae0046ae3e585"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-compose-android/1.0.2/navigationevent-compose-android-1.0.2.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-compose-android",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-compose-android/1.0.2/navigationevent-compose-android-1.0.2.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-compose-android",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-compose-android/1.0.2/navigationevent-compose-android-1.0.2.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-compose-android",
        "version": "1.0.2"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-compose-jvmstubs/1.0.2/navigationevent-compose-jvmstubs-1.0.2.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-compose-jvmstubs",
        "version": "1.0.2"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-compose-jvmstubs/1.0.2/navigationevent-compose-jvmstubs-1.0.2.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-compose-jvmstubs",
        "version": "1.0.2"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-compose-jvmstubs/1.0.2/navigationevent-compose-jvmstubs-1.0.2.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-compose-jvmstubs",
        "version": "1.0.2"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-compose-linuxx64stubs/1.0.2/navigationevent-compose-linuxx64stubs-1.0.2.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-compose-linuxx64stubs",
        "version": "1.0.2"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-compose-linuxx64stubs/1.0.2/navigationevent-compose-linuxx64stubs-1.0.2.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-compose-linuxx64stubs",
        "version": "1.0.2"
      }
    }
  ]
}