{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation3-ui/1.2.0/navigation3-ui-1.2.0.module",
    "group": "androidx.navigation3",
    "module": "navigation3-ui",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0",
      "buildId:": "16311390"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-ui.aar",
          "url": "navigation3-ui-android-1.2.0.aar",
          "size": 115891,
          "sha512": "7f44b28f72ac93ec64255b48f339157ccc628379ac6e0b8f2b415eeb0a11d30b51cb0aaeb617ba0b4fd8034d8377631e14d583ac9158703758fc5e7879d118ff",
          "sha256": "ce00086ea93af85e1adc332afae5b260707b8c6c75faa05f0fdc22995bad3173",
          "sha1": "a03288446bc3baeb8ce78a209022082c88873786",
          "md5": "6456d61fdda0d46ec467f3a0907ca249"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-ui.aar",
          "url": "navigation3-ui-android-1.2.0.aar",
          "size": 115891,
          "sha512": "7f44b28f72ac93ec64255b48f339157ccc628379ac6e0b8f2b415eeb0a11d30b51cb0aaeb617ba0b4fd8034d8377631e14d583ac9158703758fc5e7879d118ff",
          "sha256": "ce00086ea93af85e1adc332afae5b260707b8c6c75faa05f0fdc22995bad3173",
          "sha1": "a03288446bc3baeb8ce78a209022082c88873786",
          "md5": "6456d61fdda0d46ec467f3a0907ca249"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-ui-android-1.2.0-sources.jar",
          "url": "navigation3-ui-android-1.2.0-sources.jar",
          "size": 36485,
          "sha512": "d661c84853fffe45ec3350094e3c6c53b2e33a38115ff43a49d0e1efeed24a407ccb8e1b94ed9fa73ea69401bdd8be3d6857cdfe12cc1ce93ebf45103ef56bdc",
          "sha256": "7426b905f04b46a7adfe573f844a08a96ab73dcf3dcdc7b3108227fd6fea1cde",
          "sha1": "ffbc31ba10f9fa955629474f0f53aa2e1ff012d6",
          "md5": "01fbcb580184f61a94386b9b68bd95d5"
        },
        {
          "name": "navigation3-ui-1.2.0-samples-sources.jar",
          "url": "navigation3-ui-android-1.2.0-samples-sources.jar",
          "size": 19075,
          "sha512": "3bc616af32e33840089459e61d277494f3026b4aa789305567761da9f393b17d53c7b6bc95b566e2700ded2190b6dd6a7315de2aef83950f1288b760571b6e15",
          "sha256": "67c6fef16ee5f92e6999428282caab6448d11e9ea3360afcaf33eb652b2afe83",
          "sha1": "ff7c827839935be6df1bdf7276a42a201559a1f9",
          "md5": "098bc1c7ad1153158c5e20ce90284ecb"
        }
      ]
    }
  ]
}