{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation3",
    "module": "navigation3-ui",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0",
      "buildId:": "15117326"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-ui-metadata-1.1.0.jar",
          "url": "navigation3-ui-1.1.0.jar",
          "size": 19042,
          "sha512": "0b4907a2a27e4576392d8f4a0361979aeece34529920cd2a9d07b7c4657f529401ac9f018b24a8272cd15ae95a635119e62dfb5e8839a02fa46e96ca71499acf",
          "sha256": "d5d48f672ddee934972314dba220d1897b92ef4a7036511f8e2d53075c0297f2",
          "sha1": "1c9dad3485afbb2eca76af990deb6eac206a0d6c",
          "md5": "bd703985ebeb0c3671b3b4884b765b0a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-ui-kotlin-1.1.0-sources.jar",
          "url": "navigation3-ui-1.1.0-sources.jar",
          "size": 34467,
          "sha512": "4e43b528b81ba3ea4d0113b5ad9aeec1e52f284064e5ac1b832ca73acec2f8336b42f7326425f24c947c4429f97615deb30e6397e015536fe039b4aef4517f3c",
          "sha256": "706e473c3a205e1262c17a8bcd371b53d98a61fc25e715834ae4317672d42cc4",
          "sha1": "f89e373a77d6df3e952550008e8a100bc0df02d2",
          "md5": "ed6ae93a5c55eba4d09ea5cf5fe029fa"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-ui-1.1.0-multiplatform-sources.jar",
          "url": "navigation3-ui-1.1.0-multiplatform-sources.jar",
          "size": 34202,
          "sha512": "e4233468add1f9f9558041d7cc675fe09abc4404c1960e73f8eb7f9e55b18216b86a73f86d01a8680c52d667680676cc7cc448ab7526eaecf1e0603f158641b6",
          "sha256": "81a492e23ac2d8637fba4c5e837e8b46432780871f5c7b98bd2218a1ce1b8bb0",
          "sha1": "ad31a9418b5c61acf9e1e72fb506cfb9bf125ee1",
          "md5": "9e10863d49de3d7480f899b8b5175204"
        },
        {
          "name": "navigation3-ui-1.1.0-samples-sources.jar",
          "url": "navigation3-ui-1.1.0-samples-sources.jar",
          "size": 16858,
          "sha512": "fec097718e063936ecce5f2058bdf46de297770f518aa34bba5ceb7a53cfe6907258f864a99a3d7cacf49953fe8e9f473368a27b8cd41ccc66642b427fc32857",
          "sha256": "1d14472c859423a9d54f221baf986073a67741be981286fc7f5de3c25954e5c3",
          "sha1": "5269010bcdfe6e9b48d49656e387da0548011a3f",
          "md5": "6d3d38ea866bf676789e9b545ce9bcb3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "navigation3-ui-1.1.0-versionMetadata.json",
          "size": 16539,
          "sha512": "790dee969dc10480f8aed4aee64b6f0d327b70925ee0040f3cb436d0a8d2c15bd78c2fa1c593e2ffea8939511c800227b8aa82343fb3e6fced07ae6035d34918",
          "sha256": "1afaa2e34812bd8b00606717ec508bbfbd3992ea10c85685cce565653dccbf47",
          "sha1": "ef2f75c2bd43a558337e12782bc555da40c98eb4",
          "md5": "99ebda73e6b3c4a91952d78e156961cf"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation3-ui-android/1.1.0/navigation3-ui-android-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-ui-android",
        "version": "1.1.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation3-ui-android/1.1.0/navigation3-ui-android-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-ui-android",
        "version": "1.1.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation3-ui-android/1.1.0/navigation3-ui-android-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-ui-android",
        "version": "1.1.0"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation3-ui-jvmstubs/1.1.0/navigation3-ui-jvmstubs-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-ui-jvmstubs",
        "version": "1.1.0"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation3-ui-jvmstubs/1.1.0/navigation3-ui-jvmstubs-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-ui-jvmstubs",
        "version": "1.1.0"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation3-ui-jvmstubs/1.1.0/navigation3-ui-jvmstubs-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-ui-jvmstubs",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-ui-linuxx64stubs/1.1.0/navigation3-ui-linuxx64stubs-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-ui-linuxx64stubs",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-ui-linuxx64stubs/1.1.0/navigation3-ui-linuxx64stubs-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-ui-linuxx64stubs",
        "version": "1.1.0"
      }
    }
  ]
}