{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation3-runtime/1.1.0/navigation3-runtime-1.1.0.module",
    "group": "androidx.navigation3",
    "module": "navigation3-runtime",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0",
      "buildId:": "15117326"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime.aar",
          "url": "navigation3-runtime-android-1.1.0.aar",
          "size": 62725,
          "sha512": "8ce09c97a7fb3096a36d4daf17ee3b564697172862f354bed08131d0f2405459a777a59e824a7ec95ec666ed19be2bb2a29ee5a7271ef6332725bf96b27a7305",
          "sha256": "271bdb49916337dab3bee12abdfcf365231be8d5e77ea64075a0cb8ccce6f61d",
          "sha1": "8c21100924a95e67c7bc517c869f5bd4d7e4d36c",
          "md5": "586b08d254075c55d0d25b9cbd932768"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime.aar",
          "url": "navigation3-runtime-android-1.1.0.aar",
          "size": 62725,
          "sha512": "8ce09c97a7fb3096a36d4daf17ee3b564697172862f354bed08131d0f2405459a777a59e824a7ec95ec666ed19be2bb2a29ee5a7271ef6332725bf96b27a7305",
          "sha256": "271bdb49916337dab3bee12abdfcf365231be8d5e77ea64075a0cb8ccce6f61d",
          "sha1": "8c21100924a95e67c7bc517c869f5bd4d7e4d36c",
          "md5": "586b08d254075c55d0d25b9cbd932768"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-android-1.1.0-sources.jar",
          "url": "navigation3-runtime-android-1.1.0-sources.jar",
          "size": 27416,
          "sha512": "578f56815134b792df4790b671ce574b824b63da88e5e16f7470c5aea3029f80dce19e1267ef0834bd8f7e07552ad1a241b80c6f81e20a32953b60d19e8085da",
          "sha256": "2959e7f504c93451888c94b9607f19d95bdd0ece352a7d6cc33c3a3211e65c70",
          "sha1": "5ad92cade60a576085b1aaaab2b6b11091a03fa0",
          "md5": "4266a0b51c75e510419a533a49c477a3"
        },
        {
          "name": "navigation3-runtime-1.1.0-samples-sources.jar",
          "url": "navigation3-runtime-android-1.1.0-samples-sources.jar",
          "size": 14255,
          "sha512": "06093cecf047629ffb97aaed5a25f5c99e912d9357aadd960ecd0bdb0e8f87f46edf25442cb12f8fbe68d3232815f717aed3211e4b04d98ceb1c4e0da1dcca13",
          "sha256": "748f583edbd6ebf1ba00de65008e8c994d02caa6920b1c1b0e8e16dcb74d9c8e",
          "sha1": "c26765a5e058d5a9f35d1f0ed971656fb7ef2099",
          "md5": "3d489e6e5af8a57307f7788abd270f33"
        }
      ]
    }
  ]
}