{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation3-ui/1.1.0/navigation3-ui-1.1.0.module",
    "group": "androidx.navigation3",
    "module": "navigation3-ui",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0",
      "buildId:": "15117326"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-ui.aar",
          "url": "navigation3-ui-android-1.1.0.aar",
          "size": 104677,
          "sha512": "078711ddc58c9b6bd7bcd7e2c55f206081c0ef4ca5e17ca5d3f79b39eb9f07e453ffbcb550aa4935bdd7471f2d5c8e1ab0fe1a22ab070c07b3f34eb4c060a9dc",
          "sha256": "e7cdc9e25b46cb8dc4b620970c52216ef305ad2ffd679f0129b8cd5a173ced9a",
          "sha1": "eb3ada4c0fba82eeced41f90749f349df775a253",
          "md5": "c736e0981ef54945cf04443c2bdbf284"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-ui.aar",
          "url": "navigation3-ui-android-1.1.0.aar",
          "size": 104677,
          "sha512": "078711ddc58c9b6bd7bcd7e2c55f206081c0ef4ca5e17ca5d3f79b39eb9f07e453ffbcb550aa4935bdd7471f2d5c8e1ab0fe1a22ab070c07b3f34eb4c060a9dc",
          "sha256": "e7cdc9e25b46cb8dc4b620970c52216ef305ad2ffd679f0129b8cd5a173ced9a",
          "sha1": "eb3ada4c0fba82eeced41f90749f349df775a253",
          "md5": "c736e0981ef54945cf04443c2bdbf284"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-ui is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-ui-android-1.1.0-sources.jar",
          "url": "navigation3-ui-android-1.1.0-sources.jar",
          "size": 33891,
          "sha512": "22bbeb410ec1a0d1fb2081518e32c88a44adfcd92596305af6dd476bb5a2a637158e1c26e8828cd2ceaf7644b52ceb1082c6bb8e9ce9d4180afb78d70f5a9e35",
          "sha256": "ad364e0b64307169bcdf40a27004d75e5d0799e6c59ee57f4d4e63452aaa8e0b",
          "sha1": "8a241b4df6dcdc31cf18f45735719c819c7447ec",
          "md5": "089cbef3ee557ee2d434ff1204cc8752"
        },
        {
          "name": "navigation3-ui-1.1.0-samples-sources.jar",
          "url": "navigation3-ui-android-1.1.0-samples-sources.jar",
          "size": 16858,
          "sha512": "fec097718e063936ecce5f2058bdf46de297770f518aa34bba5ceb7a53cfe6907258f864a99a3d7cacf49953fe8e9f473368a27b8cd41ccc66642b427fc32857",
          "sha256": "1d14472c859423a9d54f221baf986073a67741be981286fc7f5de3c25954e5c3",
          "sha1": "5269010bcdfe6e9b48d49656e387da0548011a3f",
          "md5": "6d3d38ea866bf676789e9b545ce9bcb3"
        }
      ]
    }
  ]
}