{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation3",
    "module": "navigation3-runtime",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0",
      "buildId:": "15117326"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-metadata-1.1.0.jar",
          "url": "navigation3-runtime-1.1.0.jar",
          "size": 15140,
          "sha512": "233c4f6e9a5eed6b50d9051cce3b21cc7ef3dc6bdd89284915c367b4f4f97a4d1de6dc4b7021fa7c3f739cbbf70be153dae92b1354151a398e3cdddddfb5e00a",
          "sha256": "18b26cf3e65dbf7c82cacc504729b458cf6ec2491a05819fa97e02f1aaf8f8a5",
          "sha1": "152fce36bb65bd78c10fa29624eb900d82dee692",
          "md5": "ca69b26f762c272cd5f288f1660f8818"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-kotlin-1.1.0-sources.jar",
          "url": "navigation3-runtime-1.1.0-sources.jar",
          "size": 23454,
          "sha512": "fd3b0d03bbfe6225dec1b62f9e3586f9bd564586de5d6cbb30aea14586d2814fec3aec5368fe83bf29a747a4aff437c8e5b9bad94761acacda2cd7417f45f2a2",
          "sha256": "e00e9060d865b5d5b503382b67f36c276664d92e4018a3da7a6a3402690d9296",
          "sha1": "65dad6c3a29422391c0e83eaf4ddc26de952506f",
          "md5": "bc9a93a188af75f1c9235ff914dde85f"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-1.1.0-multiplatform-sources.jar",
          "url": "navigation3-runtime-1.1.0-multiplatform-sources.jar",
          "size": 27972,
          "sha512": "0ebf9565b4b41068bc6018165123a9e12711a964a3f27f3963be4d62737f202131b318cdd23911e4c9334beae7f6fada9043b8864ab51d01a9143f12817066e2",
          "sha256": "d6ea4316d17ce86397f2933eadc3af0ffa6fc4adb58487d97731cf7f26c4b3d4",
          "sha1": "f78b79c3167d36109d2c1b7b6929ccd0fa673d0f",
          "md5": "8e566e4019df8ccf69b3c44a203ef427"
        },
        {
          "name": "navigation3-runtime-1.1.0-samples-sources.jar",
          "url": "navigation3-runtime-1.1.0-samples-sources.jar",
          "size": 14255,
          "sha512": "06093cecf047629ffb97aaed5a25f5c99e912d9357aadd960ecd0bdb0e8f87f46edf25442cb12f8fbe68d3232815f717aed3211e4b04d98ceb1c4e0da1dcca13",
          "sha256": "748f583edbd6ebf1ba00de65008e8c994d02caa6920b1c1b0e8e16dcb74d9c8e",
          "sha1": "c26765a5e058d5a9f35d1f0ed971656fb7ef2099",
          "md5": "3d489e6e5af8a57307f7788abd270f33"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "navigation3-runtime-1.1.0-versionMetadata.json",
          "size": 13977,
          "sha512": "0dc6126310ccaa96bf95ec4e55e70d62603c88a7ad556853ccc026d177c2634070479f01462f1c8d97e3865a95d95b67708c0c15f0ef7eb7be5a39eb76cae7d5",
          "sha256": "0b907600951908d22be39ee60c03dea2e80e7d7e2fc1ba12ce5fc93fbbd64df2",
          "sha1": "85020adc4210478392081ac9b9cc4410e8263f4a",
          "md5": "39697e5a0d8d8acfa49591ea6cdcfc91"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation3-runtime-android/1.1.0/navigation3-runtime-android-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-android",
        "version": "1.1.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation3-runtime-android/1.1.0/navigation3-runtime-android-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-android",
        "version": "1.1.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation3-runtime-android/1.1.0/navigation3-runtime-android-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-android",
        "version": "1.1.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation3-runtime-desktop/1.1.0/navigation3-runtime-desktop-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-desktop",
        "version": "1.1.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation3-runtime-desktop/1.1.0/navigation3-runtime-desktop-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-desktop",
        "version": "1.1.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation3-runtime-desktop/1.1.0/navigation3-runtime-desktop-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-desktop",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-iosarm64/1.1.0/navigation3-runtime-iosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-iosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-iosarm64/1.1.0/navigation3-runtime-iosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-iosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-iosarm64/1.1.0/navigation3-runtime-iosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-iosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-iossimulatorarm64/1.1.0/navigation3-runtime-iossimulatorarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-iossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-iossimulatorarm64/1.1.0/navigation3-runtime-iossimulatorarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-iossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-iossimulatorarm64/1.1.0/navigation3-runtime-iossimulatorarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-iossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../navigation3-runtime-js/1.1.0/navigation3-runtime-js-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-js",
        "version": "1.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../navigation3-runtime-js/1.1.0/navigation3-runtime-js-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-js",
        "version": "1.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../navigation3-runtime-js/1.1.0/navigation3-runtime-js-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-js",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-linuxarm64/1.1.0/navigation3-runtime-linuxarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-linuxarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-linuxarm64/1.1.0/navigation3-runtime-linuxarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-linuxarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-linuxx64/1.1.0/navigation3-runtime-linuxx64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-linuxx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-linuxx64/1.1.0/navigation3-runtime-linuxx64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-linuxx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-macosarm64/1.1.0/navigation3-runtime-macosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-macosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-macosarm64/1.1.0/navigation3-runtime-macosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-macosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-macosarm64/1.1.0/navigation3-runtime-macosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-macosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-mingwx64/1.1.0/navigation3-runtime-mingwx64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-mingwx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-mingwx64/1.1.0/navigation3-runtime-mingwx64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-mingwx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-tvosarm64/1.1.0/navigation3-runtime-tvosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-tvosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-tvosarm64/1.1.0/navigation3-runtime-tvosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-tvosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-tvosarm64/1.1.0/navigation3-runtime-tvosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-tvosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-tvossimulatorarm64/1.1.0/navigation3-runtime-tvossimulatorarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-tvossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-tvossimulatorarm64/1.1.0/navigation3-runtime-tvossimulatorarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-tvossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-tvossimulatorarm64/1.1.0/navigation3-runtime-tvossimulatorarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-tvossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../navigation3-runtime-wasm-js/1.1.0/navigation3-runtime-wasm-js-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-wasm-js",
        "version": "1.1.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../navigation3-runtime-wasm-js/1.1.0/navigation3-runtime-wasm-js-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-wasm-js",
        "version": "1.1.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../navigation3-runtime-wasm-js/1.1.0/navigation3-runtime-wasm-js-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-wasm-js",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchosarm32/1.1.0/navigation3-runtime-watchosarm32-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchosarm32",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchosarm32/1.1.0/navigation3-runtime-watchosarm32-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchosarm32",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchosarm32/1.1.0/navigation3-runtime-watchosarm32-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchosarm32",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchosarm64/1.1.0/navigation3-runtime-watchosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchosarm64/1.1.0/navigation3-runtime-watchosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchosarm64/1.1.0/navigation3-runtime-watchosarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchosdevicearm64/1.1.0/navigation3-runtime-watchosdevicearm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchosdevicearm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchosdevicearm64/1.1.0/navigation3-runtime-watchosdevicearm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchosdevicearm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchosdevicearm64/1.1.0/navigation3-runtime-watchosdevicearm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchosdevicearm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchossimulatorarm64/1.1.0/navigation3-runtime-watchossimulatorarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchossimulatorarm64/1.1.0/navigation3-runtime-watchossimulatorarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-runtime-watchossimulatorarm64/1.1.0/navigation3-runtime-watchossimulatorarm64-1.1.0.module",
        "group": "androidx.navigation3",
        "module": "navigation3-runtime-watchossimulatorarm64",
        "version": "1.1.0"
      }
    }
  ]
}