// AndroidOnly: WP-004 Strict test-only reader for independently copied protocol fixtures.
package com.meshcoreone.android.core.testing

import com.meshcoreone.android.core.protocol.bytes.Bytes
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.nio.ByteBuffer
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.util.Collections

data class ReferenceVector(
    val id: String,
    val category: String,
    val role: String,
    val bytes: Bytes,
    val sourcePath: String,
    val sourceBlob: String,
    val sourceLine: Int,
    val protocolVersion: String,
)

class FixtureFormatException(message: String) : IllegalArgumentException(message)

object ReferenceVectorFixture {
    const val SOURCE_SHA = "db14559b39d32322b06477c6ae676112f583db50"
    private const val MAX_BYTES = 1_048_576
    private const val VERSION = "pinned-reference-snapshot"
    private const val HEADER =
        "id\tcategory\trole\thex\tbyte_count\tsource_path\tblob_sha\tsource_line\tprotocol_version"
    private val hexPattern = Regex("(?:[0-9a-f]{2})*")
    private val blobPattern = Regex("[0-9a-f]{40}")

    fun read(input: InputStream): List<ReferenceVector> {
        val output = ByteArrayOutputStream()
        val buffer = ByteArray(4096)
        while (true) {
            val count = input.read(buffer)
            if (count == -1) break
            if (count == 0) throw FixtureFormatException("Fixture stream made no progress")
            if (output.size() + count > MAX_BYTES) throw FixtureFormatException("Fixture exceeds size bound")
            output.write(buffer, 0, count)
        }
        val decoder = StandardCharsets.UTF_8.newDecoder()
            .onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT)
        val text = decoder.decode(ByteBuffer.wrap(output.toByteArray())).toString()
        val lines = text.lineSequence().toList()
        val notice = "# Generated by tools/android-port/extract_vectors.py from $SOURCE_SHA; MIT MeshCore reference fixtures."
        if (lines.size < 3 || lines[0] != notice || lines[1] != HEADER) {
            throw FixtureFormatException("Missing or stale source/header")
        }
        val vectors = mutableListOf<ReferenceVector>()
        val identities = mutableSetOf<String>()
        for ((index, line) in lines.drop(2).withIndex()) {
            if (line.isEmpty() && index == lines.size - 3) continue
            val fields = line.split('\t')
            if (fields.size != 9 || fields[0].isBlank() || !identities.add(fields[0])) {
                throw FixtureFormatException("Malformed or duplicate vector at line ${index + 3}")
            }
            val count = fields[4].toIntOrNull()
            val sourceLine = fields[7].toIntOrNull()
            if (!hexPattern.matches(fields[3]) || count == null || count < 0 || fields[3].length / 2 != count ||
                !blobPattern.matches(fields[6]) || sourceLine == null || sourceLine < 1 || fields[8] != VERSION ||
                fields[1].isBlank() || fields[2].isBlank() || fields[5].isBlank()
            ) {
                throw FixtureFormatException("Invalid vector bytes/provenance at line ${index + 3}")
            }
            val bytes = Bytes.fromHex(fields[3])
            vectors.add(ReferenceVector(fields[0], fields[1], fields[2], bytes,
                fields[5], fields[6], sourceLine, fields[8]))
        }
        if (vectors.isEmpty()) throw FixtureFormatException("Zero independent fixture vectors")
        return Collections.unmodifiableList(vectors)
    }
}
