"""WP-005: deterministic, pinned Apple localization -> Android resources.

Only the declared generated outputs are writable. The Swift tree is always an
immutable input, including in tests and --write mode. No third-party packages.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import unittest
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape


REFERENCE = "db14559b39d32322b06477c6ae676112f583db50"
REFERENCE_TREE = "8918fdc604341e6996a68c88f6bb1c02b9c2f87e"
REPOSITORY = Path(__file__).resolve().parents[2]
MODULE = "android/core/l10n"
KEY_MAP = "docs/android/generated/l10n-key-map.json"
CONFIG = "docs/android/localization/exclusions.json"
ADAPTATIONS = "docs/android/localization/format-adaptations.json"
GENERATOR = "tools/android-port/l10n_convert.py"
KOTLIN = MODULE + "/src/main/kotlin/com/meshcoreone/android/core/l10n/generated"
ORACLE = MODULE + "/src/test/resources/l10n-source-oracle.json"
LOCALES = {
    "en": {"tag": "en", "directory": "values"},
    "de": {"tag": "de", "directory": "values-de"},
    "es": {"tag": "es", "directory": "values-es"},
    "fr": {"tag": "fr", "directory": "values-fr"},
    "it": {"tag": "it", "directory": "values-it"},
    "ko": {"tag": "ko", "directory": "values-ko"},
    "nl": {"tag": "nl", "directory": "values-nl"},
    "pl": {"tag": "pl", "directory": "values-pl"},
    "pt": {"tag": "pt-PT", "directory": "values-pt"},
    "ru": {"tag": "ru", "directory": "values-ru"},
    "uk": {"tag": "uk", "directory": "values-uk"},
    "zh-Hans": {"tag": "zh-Hans", "directory": "values-b+zh+Hans"},
}
SCAFFOLD_TABS = {
    "tab_chats": "tabs.chats", "tab_nodes": "tabs.nodes", "tab_map": "tabs.map",
    "tab_tools": "tabs.tools", "tab_settings": "tabs.settings",
}
QUANTITIES = ("zero", "one", "two", "few", "many", "other")
ROOTS = ("MC1/Resources/Localization/", "MC1Widgets/Resources/")
CATALOG = "MC1/Resources/AppShortcuts.xcstrings"
CONTEXT = (
    "TRANSLATIONS.md",
    "swiftgen.yml",
    "MC1/Resources/Generated/L10n.swift",
    "MC1Tests/Localization/AirtimePercentLabelTests.swift",
    "MC1Tests/Localization/RegionalSubdivisionLocalizationTests.swift",
    "MC1Services/Sources/MC1Services/Services/RegionalAreas.swift",
    "MC1Tests/Intents/IntentMetadataLocalizationTests.swift",
    "MC1/Intents/SendMessageIntent.swift",
    "MC1/Intents/SendAdvertIntent.swift",
    "LICENSE",
    "MeshCore/LICENSE",
)
XML_HEADER = '<?xml version="1.0" encoding="utf-8"?>\n'
NOTICE = (
    "Generated by tools/android-port/l10n_convert.py; DO NOT EDIT. "
    f"GPLv3 app translations at {REFERENCE}; provenance: {KEY_MAP}."
)


class ConversionError(ValueError):
    """Invalid/unsupported input, source drift, or generated-output drift."""


def fail(location: str, message: str) -> None:
    raise ConversionError(f"{location}: {message}")


def host_path(root: Path, git_path: str) -> Path:
    return root.joinpath(*git_path.split("/"))


def decode_apple(data: bytes, location: str) -> str:
    try:
        if data.startswith((b"\xff\xfe\x00\x00", b"\x00\x00\xfe\xff")):
            fail(location, "UTF-32 is not a supported Apple strings encoding")
        encoding = "utf-16" if data.startswith((b"\xff\xfe", b"\xfe\xff")) else "utf-8-sig"
        return data.decode(encoding)
    except UnicodeError as error:
        fail(location, f"invalid UTF-8/UTF-16 input: {error}")


class OpenStepParser:
    """A character lexer/parser, not a line-oriented strings-file regex."""

    def __init__(self, text: str, location: str):
        self.text = text
        self.location = location
        self.index = 0

    def error(self, message: str) -> None:
        line = self.text.count("\n", 0, self.index) + 1
        fail(f"{self.location}:{line}", message)

    def trivia(self) -> None:
        while self.index < len(self.text):
            if self.text[self.index].isspace():
                self.index += 1
            elif self.text.startswith("//", self.index):
                end = self.text.find("\n", self.index + 2)
                self.index = len(self.text) if end == -1 else end + 1
            elif self.text.startswith("/*", self.index):
                end = self.text.find("*/", self.index + 2)
                if end == -1:
                    self.error("unterminated block comment")
                if "/*" in self.text[self.index + 2 : end]:
                    self.error("nested block comments are unsupported")
                self.index = end + 2
            else:
                break

    def punctuation(self, expected: str) -> None:
        self.trivia()
        if self.index >= len(self.text) or self.text[self.index] != expected:
            self.error(f"expected {expected!r}")
        self.index += 1

    def quoted(self) -> str:
        self.punctuation('"')
        result: list[str] = []
        simple = {
            "n": "\n", "r": "\r", "t": "\t", "b": "\b", "f": "\f",
            "a": "\a", "v": "\v", "\\": "\\", '"': '"', "'": "'", "?": "?",
        }
        while self.index < len(self.text):
            char = self.text[self.index]
            self.index += 1
            if char == '"':
                value = "".join(result)
                try:
                    return value.encode("utf-16", "surrogatepass").decode("utf-16")
                except UnicodeError:
                    self.error("unpaired Unicode surrogate")
            if char != "\\":
                result.append(char)
                continue
            if self.index == len(self.text):
                self.error("unterminated string escape")
            char = self.text[self.index]
            self.index += 1
            if char in simple:
                result.append(simple[char])
            elif char in "\r\n":
                if char == "\r" and self.text[self.index : self.index + 1] == "\n":
                    self.index += 1
            elif char in "uU":
                digits = self.text[self.index : self.index + 4]
                if len(digits) != 4 or any(c not in "0123456789abcdefABCDEF" for c in digits):
                    self.error("Unicode escape requires exactly four hexadecimal digits")
                result.append(chr(int(digits, 16)))
                self.index += 4
            elif char in "01234567":
                digits = char
                while len(digits) < 3 and self.text[self.index : self.index + 1] in tuple("01234567"):
                    digits += self.text[self.index]
                    self.index += 1
                result.append(chr(int(digits, 8)))
            else:
                self.error(f"unsupported string escape \\{char}")
        self.error("unterminated quoted string")

    def parse(self) -> dict[str, str]:
        result: dict[str, str] = {}
        while True:
            self.trivia()
            if self.index == len(self.text):
                return result
            key = self.quoted()
            if not key:
                self.error("empty localization key")
            self.punctuation("=")
            value = self.quoted()
            self.punctuation(";")
            if key in result:
                self.error(f"duplicate key {key!r}")
            result[key] = value


def parse_strings(data: bytes, location: str) -> dict[str, str]:
    return OpenStepParser(decode_apple(data, location), location).parse()


def unique_json(data: str, location: str) -> dict:
    def pairs(items):
        result = {}
        for key, value in items:
            if key in result:
                fail(location, f"duplicate JSON key {key!r}")
            result[key] = value
        return result

    try:
        result = json.loads(data, object_pairs_hook=pairs)
    except json.JSONDecodeError as error:
        fail(location, f"invalid JSON: {error}")
    if not isinstance(result, dict):
        fail(location, "expected a JSON object")
    return result


def parse_plist(data: bytes, location: str) -> dict:
    text = decode_apple(data, location)
    if "<!ENTITY" in text:
        fail(location, "XML entities are forbidden")
    doctypes = re.findall(r"<!DOCTYPE[^>]*>", text)
    allowed = '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
    if doctypes and doctypes != [allowed]:
        fail(location, "unsupported plist DOCTYPE (no external/custom DTDs)")
    try:
        root = ET.fromstring(text)
    except ET.ParseError as error:
        fail(location, f"invalid plist XML: {error}")
    if root.tag != "plist" or root.attrib != {"version": "1.0"} or len(root) != 1:
        fail(location, "expected a version 1.0 XML plist with one dictionary")
    if (root.text or "").strip() or (root[0].tail or "").strip():
        fail(location, "unexpected text outside the plist dictionary")

    def value(node: ET.Element, at: str):
        if node.attrib:
            fail(at, f"unexpected attributes on {node.tag}")
        if node.tag == "string" and not len(node):
            return node.text or ""
        if node.tag != "dict" or (node.text or "").strip():
            fail(at, f"unsupported plist value {node.tag!r}")
        children = list(node)
        if any((child.tail or "").strip() for child in children):
            fail(at, "unexpected text between plist keys/values")
        if len(children) % 2:
            fail(at, "plist dictionary has an unmatched key/value")
        result = {}
        for index in range(0, len(children), 2):
            key = children[index]
            if key.tag != "key" or key.attrib or len(key) or not key.text:
                fail(at, "plist dictionary requires nonempty string keys")
            if key.text in result:
                fail(at, f"duplicate plist key {key.text!r}")
            result[key.text] = value(children[index + 1], f"{at}/{key.text}")
        return result

    parsed = value(root[0], location)
    if not isinstance(parsed, dict):
        fail(location, "stringsdict root must be a dictionary")
    return parsed


@dataclass(frozen=True)
class Format:
    android: str
    arguments: tuple[tuple[int, str], ...]


def parse_format(text: str, location: str, tokens: tuple[str, ...] = ()) -> Format:
    output: list[str] = []
    arguments: dict[int, str] = {}
    index = 0
    implicit = 1
    modes: set[str] = set()

    def argument(position: int, kind: str) -> None:
        if position < 1 or position > 32:
            fail(location, f"argument position {position} is outside 1..32")
        if position in arguments and arguments[position] != kind:
            fail(location, f"argument {position} has conflicting types")
        arguments[position] = kind

    while index < len(text):
        if text.startswith("${", index):
            end = text.find("}", index + 2)
            if end == -1:
                fail(location, "unterminated catalog parameter")
            name = text[index + 2 : end]
            if name not in tokens:
                fail(location, f"unknown catalog parameter {name!r}")
            position = tokens.index(name) + 1
            argument(position, "string")
            output.append(f"%{position}$s")
            index = end + 1
            continue
        if text[index] != "%":
            output.append(text[index])
            index += 1
            continue
        start = index
        index += 1
        if index == len(text) or text[index] in "),;:!?\"'\n\r":
            output.append("%%")
            continue
        if text[index] == "%":
            output.append("%%")
            index += 1
            continue
        position_start = index
        while index < len(text) and text[index].isdigit() and text[index].isascii():
            index += 1
        if index < len(text) and text[index] == "$":
            if index == position_start:
                fail(location, "missing positional argument index")
            position = int(text[position_start:index])
            index += 1
            modes.add("explicit")
        else:
            index = position_start
            position = implicit
            implicit += 1
            modes.add("implicit")
        flags_start = index
        while index < len(text) and text[index] in "-+ #0":
            index += 1
        flags = text[flags_start:index]
        if len(set(flags)) != len(flags) or ("+" in flags and " " in flags) or ("-" in flags and "0" in flags):
            fail(location, f"lossy/conflicting printf flags in {text[start:index]!r}")
        width_start = index
        while index < len(text) and text[index].isdigit() and text[index].isascii():
            index += 1
        width = text[width_start:index]
        precision = ""
        if index < len(text) and text[index] == ".":
            index += 1
            precision_start = index
            while index < len(text) and text[index].isdigit() and text[index].isascii():
                index += 1
            precision = "." + (text[precision_start:index] or "0")
        length = ""
        if text[index:index + 2] in ("ll", "hh"):
            length = text[index:index + 2]
            index += 2
        elif text[index:index + 1] in tuple("lhzjtL"):
            length = text[index]
            index += 1
        if index == len(text):
            fail(location, f"incomplete printf directive {text[start:]!r}")
        conversion = text[index]
        index += 1
        if conversion == "@" and not length and not precision and set(flags) <= {"-"}:
            kind, java = "string", "s"
        elif conversion in "di" and length in ("", "l", "ll") and not precision and "#" not in flags:
            kind, java = ("int" if not length else "long"), "d"
        elif conversion == "f" and length in ("", "l"):
            kind, java = "double", "f"
        else:
            fail(location, f"unsupported/lossy printf directive {text[start:index]!r}")
        if ("-" in flags or "0" in flags) and not width:
            fail(location, "printf padding flags require a width")
        argument(position, kind)
        output.append(f"%{position}${flags}{width}{precision}{java}")
    if len(modes) > 1 or (modes and tokens):
        fail(location, "mixed positional/implicit/named argument addressing")
    converted = "".join(output)
    if not arguments:
        converted = converted.replace("%%", "%")
    return Format(converted, tuple(sorted(arguments.items())))


@dataclass(frozen=True)
class Text:
    raw: str
    path: str
    format: Format
    tokens: tuple[str, ...] = ()
    adaptation: str | None = None


@dataclass(frozen=True)
class Plural:
    path: str
    quantity: int
    value_type: str
    raw: dict[str, str]
    formats: dict[str, Format]
    arguments: tuple[tuple[int, str], ...]


def parse_plurals(data: bytes, location: str) -> dict[str, Plural]:
    result = {}
    for key, definition in parse_plist(data, location).items():
        at = f"{location}/{key}"
        if not isinstance(definition, dict):
            fail(at, "plural definition must be a dictionary")
        outer = definition.get("NSStringLocalizedFormatKey")
        if not isinstance(outer, str):
            fail(at, "missing NSStringLocalizedFormatKey")
        token = re.fullmatch(r"%(?:([1-9][0-9]*)\$)?#@([A-Za-z_][A-Za-z_0-9]*)@", outer)
        if token is None:
            fail(at, "only a single whole-string plural variable is supported; no ambiguous composition")
        quantity = int(token[1] or "1")
        variable = token[2]
        if set(definition) != {"NSStringLocalizedFormatKey", variable}:
            fail(at, "unused or multiple plural variables")
        rule = definition[variable]
        if not isinstance(rule, dict) or rule.get("NSStringFormatSpecTypeKey") != "NSStringPluralRuleType":
            fail(at, "expected NSStringPluralRuleType")
        value_type = rule.get("NSStringFormatValueTypeKey")
        if value_type not in ("d", "ld", "lld"):
            fail(at, f"unsupported plural quantity type {value_type!r}")
        raw = {k: v for k, v in rule.items() if k in QUANTITIES}
        if set(rule) - set(QUANTITIES) - {"NSStringFormatSpecTypeKey", "NSStringFormatValueTypeKey"}:
            fail(at, "unknown plural metadata/quantity")
        if "other" not in raw or any(not isinstance(value, str) for value in raw.values()):
            fail(at, "plural requires an other string and string-valued quantities")
        formats = {q: parse_format(value, f"{at}/{q}") for q, value in raw.items()}
        kind = "int" if value_type == "d" else "long"
        signatures = []
        for q, fmt in formats.items():
            args = dict(fmt.arguments)
            if quantity in args and args[quantity] != kind:
                fail(f"{at}/{q}", "plural quantity/format argument types disagree")
            args[quantity] = kind
            signatures.append(tuple(sorted(args.items())))
        if len(set(signatures)) != 1:
            fail(at, "plural branches disagree on non-quantity arguments")
        result[key] = Plural(location, quantity, value_type, raw, formats, signatures[0])
    return result


def parse_catalog(data: bytes, location: str) -> dict[str, dict[str, Text]]:
    catalog = unique_json(decode_apple(data, location), location)
    if set(catalog) != {"sourceLanguage", "strings", "version"} or catalog["sourceLanguage"] != "en" or catalog["version"] != "1.0":
        fail(location, "unsupported xcstrings schema/version/source language")
    if not isinstance(catalog["strings"], dict):
        fail(location, "xcstrings strings must be an object")
    result = {}
    for key, definition in catalog["strings"].items():
        at = f"{location}/{key}"
        if not isinstance(definition, dict) or set(definition) - {"comment", "extractionState", "localizations"}:
            fail(at, "unsupported xcstrings definition (variations/substitutions are not silently dropped)")
        if "comment" in definition and not isinstance(definition["comment"], str):
            fail(at, "xcstrings comment must be a string")
        if "extractionState" in definition and definition["extractionState"] not in ("stale", "manual", "extracted"):
            fail(at, "unsupported xcstrings extraction state")
        localizations = definition.get("localizations")
        if not isinstance(localizations, dict) or "en" not in localizations:
            fail(at, "catalog key needs an explicit English source stringUnit")
        english = localizations["en"]
        if not isinstance(english, dict) or set(english) != {"stringUnit"}:
            fail(at, "unsupported English xcstrings localization")
        unit = english["stringUnit"]
        if not isinstance(unit, dict) or not isinstance(unit.get("value"), str):
            fail(at, "missing English stringUnit value")
        tokens = tuple(dict.fromkeys(re.findall(r"\$\{([^}]+)\}", unit["value"])))
        if any(not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name) for name in tokens):
            fail(at, "invalid named catalog parameter")
        translations = {}
        for locale, localized in localizations.items():
            if locale not in LOCALES:
                fail(at, f"unmapped locale {locale!r}")
            if not isinstance(localized, dict) or set(localized) != {"stringUnit"}:
                fail(at, "unsupported xcstrings localization")
            value = localized["stringUnit"]
            if not isinstance(value, dict) or set(value) != {"state", "value"} or value["state"] != "translated" or not isinstance(value["value"], str):
                fail(at, "unsupported/nontranslated stringUnit")
            fmt = parse_format(value["value"], f"{at}/{locale}", tokens)
            if set(re.findall(r"\$\{([^}]+)\}", value["value"])) != set(tokens):
                fail(at, f"{locale} drops/adds a named catalog parameter")
            translations[locale] = Text(value["value"], location, fmt, tokens)
        result[key] = translations
    return result


def named_parameters(text: str, location: str) -> tuple[str, ...]:
    names = tuple(dict.fromkeys(re.findall(r"\$\{([^}]+)\}", text)))
    if any(not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name) for name in names):
        fail(location, "invalid named parameter")
    return names


def slug(value: str, location: str) -> str:
    name = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    if not name or not any(c.isalpha() for c in name):
        fail(location, "key cannot be mapped to a meaningful stable Android name")
    return name


def android_name(domain: str, table: str, key: str) -> str:
    return f"l10n_{slug(domain, domain)}_{slug(table, table)}_{slug(key, key)}"


def kotlin_name(key: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", key)
    name = parts[0][0].lower() + parts[0][1:] + "".join(p[0].upper() + p[1:] for p in parts[1:])
    return f"`{name}`"


def android_xml_text(value: str, location: str) -> str:
    for char in value:
        code = ord(char)
        if not (code in (9, 10, 13) or 0x20 <= code <= 0xD7FF or 0xE000 <= code <= 0xFFFD or 0x10000 <= code <= 0x10FFFF):
            fail(location, f"invalid XML character U+{code:04X}")
    value = (value.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")
             .replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\u000d")
             .replace("@", "\\@").replace("?", "\\?"))
    return '"' + escape(value) + '"'


@dataclass
class Message:
    domain: str
    table: str
    key: str
    strings: dict[str, Text] = field(default_factory=dict)
    plurals: dict[str, Plural] = field(default_factory=dict)

    @property
    def name(self) -> str:
        return android_name(self.domain, self.table, self.key)

    @property
    def base(self) -> Text | Plural:
        return self.plurals.get("en") or self.strings["en"]

    def effective(self, locale: str) -> Text | Plural:
        return (self.plurals if isinstance(self.base, Plural) else self.strings).get(locale) or self.base

    def validate(self) -> None:
        at = f"{self.domain}/{self.table}/{self.key}"
        if "en" not in self.strings and "en" not in self.plurals:
            fail(at, "unmapped translated key: no English source")
        base = self.base
        signature = base.arguments if isinstance(base, Plural) else base.format.arguments
        if tuple(p for p, _ in signature) != tuple(range(1, len(signature) + 1)):
            fail(at, "argument signature has missing positions")
        for locale, value in self.strings.items():
            if value.format.arguments != signature:
                fail(f"{value.path}/{self.key}", f"{locale} argument signature {value.format.arguments} != English {signature}")
        for locale, value in self.plurals.items():
            if not isinstance(base, Plural) or (value.arguments, value.quantity, value.value_type) != (signature, base.quantity, base.value_type):
                fail(f"{value.path}/{self.key}", f"{locale} inconsistent plural quantity/signature")
        if isinstance(base, Plural):
            for locale in self.strings.keys() - self.plurals.keys():
                fail(f"{self.strings[locale].path}/{self.key}", "localized flat fallback without its plural dictionary would change quantity semantics")


def assert_source_bytes(actual: bytes, pinned: bytes, location: str) -> None:
    binary_text = pinned.startswith((b"\xff\xfe", b"\xfe\xff"))
    equivalent = actual == pinned if binary_text else actual.replace(b"\r\n", b"\n") == pinned.replace(b"\r\n", b"\n")
    if not equivalent:
        fail(location, f"read-only source drift from {REFERENCE}")


def pinned_inputs(root: Path) -> tuple[dict[str, bytes], list[dict]]:
    manifest_path = "docs/android/port-manifest.json"
    manifest = unique_json(host_path(root, manifest_path).read_text(encoding="utf-8"), manifest_path)
    if manifest.get("reference", {}).get("commit") != REFERENCE or manifest["reference"].get("tree_sha") != REFERENCE_TREE:
        fail(manifest_path, "stale/changed reference pin; never silently advance it")
    wp = [wp for wp in manifest["work_packages"] if wp["id"] == "WP-005"]
    if len(wp) != 1 or wp[0]["owner"] != "localization-engineer" or wp[0]["depends_on"] != ["WP-003"]:
        fail(manifest_path, "unexpected WP-005 ownership/prerequisites")
    tree = subprocess.run(["git", "rev-parse", REFERENCE + "^{tree}"], cwd=root, capture_output=True, check=True, text=True).stdout.strip()
    if tree != REFERENCE_TREE:
        fail(REFERENCE, "Git reference tree disagrees with manifest")
    listing = subprocess.run(["git", "ls-tree", "-r", "--full-tree", REFERENCE], cwd=root, capture_output=True, check=True, text=True).stdout
    blobs = {}
    for line in listing.splitlines():
        metadata, path = line.split("\t", 1)
        blobs[path] = metadata.split()[2]
    paths = sorted(path for path in blobs if path.startswith(ROOTS) and Path(path).suffix in (".strings", ".stringsdict"))
    paths += [CATALOG] + list(CONTEXT)
    current = {
        file.relative_to(root).as_posix()
        for prefix in ROOTS for file in host_path(root, prefix).rglob("*")
        if file.is_file() and file.suffix in (".strings", ".stringsdict", ".xcstrings")
    }
    if current != set(paths) - {CATALOG} - set(CONTEXT):
        fail("localization inputs", f"added/missing source files: {sorted(current ^ (set(paths) - {CATALOG} - set(CONTEXT)))}")
    inventory = {entry["path"]: entry for entry in manifest["inventory"]}
    for path in paths:
        if path not in blobs or inventory.get(path, {}).get("blob_sha") != blobs[path]:
            fail(path, "source blob is missing or disagrees with approved inventory")
    batch = subprocess.run(
        ["git", "cat-file", "--batch"], cwd=root,
        input="".join(f"{REFERENCE}:{path}\n" for path in paths).encode(),
        capture_output=True, check=True,
    ).stdout
    position = 0
    inputs = {}
    provenance = []
    for path in paths:
        end = batch.index(b"\n", position)
        header = batch[position:end].decode().split()
        if len(header) != 3 or header[0] != blobs[path] or header[1] != "blob":
            fail(path, "invalid pinned Git blob response")
        size = int(header[2])
        data = batch[end + 1 : end + 1 + size]
        position = end + 2 + size
        digest = hashlib.sha1(f"blob {size}\0".encode() + data).hexdigest()
        if digest != blobs[path]:
            fail(path, "Git blob bytes do not match inventory revision")
        assert_source_bytes(host_path(root, path).read_bytes(), data, path)
        inputs[path] = data
        provenance.append({
            "path": path, "blob_sha": blobs[path], "sha256": hashlib.sha256(data).hexdigest(),
            "bytes": size, "role": "context" if path in CONTEXT else "localization",
        })
    if position != len(batch):
        fail("Git inputs", "unexpected trailing blob response")
    return inputs, provenance


def load_format_adaptations(root: Path) -> dict[tuple[str, str, str, str], dict]:
    declaration = unique_json(host_path(root, ADAPTATIONS).read_text(encoding="utf-8"), ADAPTATIONS)
    if set(declaration) != {"source_pin", "adaptations"} or declaration["source_pin"] != REFERENCE:
        fail(ADAPTATIONS, "stale/invalid native-format adaptation declaration")
    result = {}
    fields = {
        "id", "domain", "table", "key", "locale", "source_blob_sha", "source_value_sha256",
        "argument", "expected_source", "expected_english", "expected_android_format",
        "source_token", "android_token", "reason",
    }
    for entry in declaration["adaptations"]:
        if not isinstance(entry, dict) or set(entry) != fields or not entry["reason"]:
            fail(ADAPTATIONS, "invalid exact native-format adaptation")
        identity = entry["domain"], entry["table"], entry["key"], entry["locale"]
        if identity != ("app", "Contacts", "contacts.results.comparison", "zh-Hans") or identity in result:
            fail(ADAPTATIONS, "only the identified pinned integer/object typo may be adapted")
        if entry["argument"] != 1 or entry["source_token"] != "%@" or entry["android_token"] != "%d":
            fail(ADAPTATIONS, "the bounded correction must preserve the canonical integer argument")
        result[identity] = entry
    if len(result) != 1:
        fail(ADAPTATIONS, "expected the single explicit pinned-source format correction")
    return result


def load_messages(
    inputs: dict[str, bytes], adaptations: dict[tuple[str, str, str, str], dict] | None = None,
) -> tuple[list[Message], dict[str, int]]:
    adaptations = adaptations or {}
    messages: dict[tuple[str, str, str], Message] = {}
    counts = {}
    locale_tables: dict[str, set[tuple[str, str, str]]] = {locale: set() for locale in LOCALES}
    for path, data in sorted(inputs.items()):
        if path in CONTEXT:
            continue
        if path == CATALOG:
            catalog = parse_catalog(data, path)
            counts[path] = len(catalog)
            for key, texts in catalog.items():
                messages[("shortcut", "AppShortcuts", key)] = Message("shortcut", "AppShortcuts", key, texts)
            continue
        parts = path.split("/")
        locale = parts[-2].removesuffix(".lproj")
        if locale not in LOCALES:
            fail(path, f"unmapped Apple locale {locale!r}")
        domain = "app" if path.startswith(ROOTS[0]) else "widget"
        table = Path(path).stem
        extension = Path(path).suffix
        locale_tables[locale].add((domain, table, extension))
        parsed = parse_strings(data, path) if extension == ".strings" else parse_plurals(data, path)
        counts[path] = len(parsed)
        for key, value in parsed.items():
            message = messages.setdefault((domain, table, key), Message(domain, table, key))
            if extension == ".strings":
                message.strings[locale] = Text(value, path, Format("", ()))
            else:
                message.plurals[locale] = value
    for locale, tables in locale_tables.items():
        if tables != locale_tables["en"]:
            fail(locale, f"missing/extra localization tables: {sorted(tables ^ locale_tables['en'])}")
    names = {}
    applied = set()
    for message in messages.values():
        if "en" in message.strings:
            tokens = named_parameters(message.strings["en"].raw, message.key)
            for locale, value in list(message.strings.items()):
                if set(named_parameters(value.raw, value.path)) != set(tokens):
                    fail(f"{value.path}/{message.key}", "localized string drops/adds a named parameter")
                message.strings[locale] = Text(
                    value.raw, value.path, parse_format(value.raw, f"{value.path}/{message.key}", tokens), tokens,
                )
                identity = message.domain, message.table, message.key, locale
                if identity in adaptations:
                    entry = adaptations[identity]
                    source_data = inputs[value.path]
                    source_blob = hashlib.sha1(f"blob {len(source_data)}\0".encode() + source_data).hexdigest()
                    if source_blob != entry["source_blob_sha"] or hashlib.sha256(value.raw.encode()).hexdigest() != entry["source_value_sha256"]:
                        fail(f"{value.path}/{message.key}", "stale native-format blob/value fingerprint")
                    if value.raw != entry["expected_source"] or message.strings["en"].raw != entry["expected_english"]:
                        fail(f"{value.path}/{message.key}", "stale native-format correction: original source copy changed")
                    original = message.strings[locale]
                    english = parse_format(entry["expected_english"], message.key)
                    if original.format.arguments != ((1, "string"), (2, "string")) or english.arguments != ((1, "int"), (2, "string")):
                        fail(f"{value.path}/{message.key}", "native correction no longer matches the independent integer consumer")
                    corrected = value.raw.replace(entry["source_token"], entry["android_token"], 1)
                    corrected_format = parse_format(corrected, f"{value.path}/{message.key}", tokens)
                    if corrected_format.android != entry["expected_android_format"]:
                        fail(f"{value.path}/{message.key}", "native-format replacement differs from the declared output")
                    message.strings[locale] = Text(value.raw, value.path, corrected_format, tokens, entry["id"])
                    applied.add(identity)
        message.validate()
        if message.name in names:
            fail(message.key, f"Android name collision {message.name!r} with {names[message.name]!r}")
        names[message.name] = (message.domain, message.table, message.key)
    if applied != set(adaptations):
        fail(ADAPTATIONS, "unapplied/unknown native-format correction")
    return sorted(messages.values(), key=lambda m: m.name), counts


def exclusions(root: Path, messages: list[Message]) -> dict[tuple[str, str, str], str]:
    declaration = unique_json(host_path(root, CONFIG).read_text(encoding="utf-8"), CONFIG)
    if set(declaration) != {"source_pin", "basis", "keys"} or declaration["source_pin"] != REFERENCE or not declaration["basis"]:
        fail(CONFIG, "invalid key-level exclusion declaration/reference")
    known = {(m.domain, m.table, m.key) for m in messages}
    result = {}
    for entry in declaration["keys"]:
        if not isinstance(entry, dict) or set(entry) != {"domain", "table", "key", "reason"} or not entry["reason"]:
            fail(CONFIG, "exclusions require an exact domain/table/key and reason")
        identity = entry["domain"], entry["table"], entry["key"]
        if identity in result or identity not in known or identity[:2] != ("app", "Settings"):
            fail(CONFIG, f"duplicate, nonexistent, or non-billing-domain exclusion {identity!r}")
        result[identity] = entry["reason"]
    return result


def resource_xml(messages: list[Message], locale: str, plural: bool) -> bytes:
    lines = [XML_HEADER.rstrip(), f"<!-- {NOTICE} -->", "<resources>"]
    for message in messages:
        base = message.base
        if isinstance(base, Plural) != plural:
            continue
        translated = locale in (message.plurals if plural else message.strings)
        if locale != "en" and not translated:
            continue
        value = message.effective(locale)
        if isinstance(value, Plural):
            lines.append(f'    <plurals name="{message.name}">')
            for quantity in QUANTITIES:
                if quantity in value.formats:
                    body = android_xml_text(value.formats[quantity].android, f"{value.path}/{message.key}/{quantity}")
                    lines.append(f'        <item quantity="{quantity}">{body}</item>')
            lines.append("    </plurals>")
        else:
            body = android_xml_text(value.format.android, f"{value.path}/{message.key}")
            formatted = "true" if value.format.arguments else "false"
            lines.append(f'    <string name="{message.name}" formatted="{formatted}">{body}</string>')
    lines.append("</resources>")
    xml = ("\n".join(lines) + "\n").encode()
    validate_resource_xml(xml, f"{locale}/{'plurals' if plural else 'strings'}")
    return xml


def validate_resource_xml(data: bytes, location: str) -> None:
    try:
        root = ET.fromstring(data)
    except ET.ParseError as error:
        fail(location, f"invalid generated XML: {error}")
    if root.tag != "resources" or root.attrib:
        fail(location, "invalid Android resource root")
    names = set()
    for node in root:
        name = node.get("name", "")
        if not re.fullmatch(r"[a-z][a-z0-9_]*", name) or name in names:
            fail(location, f"illegal/duplicate Android resource name {name!r}")
        names.add(name)
        if node.tag == "string":
            if len(node) or set(node.attrib) != {"name", "formatted"} or node.get("formatted") not in ("true", "false"):
                fail(location, f"invalid string resource {name}")
        elif node.tag == "plurals":
            quantities = [item.get("quantity") for item in node]
            if set(node.attrib) != {"name"} or "other" not in quantities or len(set(quantities)) != len(quantities):
                fail(location, f"invalid plural resource {name}")
            if any(item.tag != "item" or set(item.attrib) != {"quantity"} or len(item) or item.get("quantity") not in QUANTITIES for item in node):
                fail(location, f"invalid plural item {name}")
        else:
            fail(location, f"unsupported resource {node.tag}")


def kotlin_table(messages: list[Message], domain: str, table: str) -> tuple[str, bytes]:
    object_name = domain.title() + table + "Strings"
    lines = [
        f"// {NOTICE}",
        "package com.meshcoreone.android.core.l10n.generated",
        "",
        "import android.content.res.Resources",
        "import com.meshcoreone.android.core.l10n.L10nFormatting",
        "import com.meshcoreone.android.core.l10n.R",
        "",
        f"object {object_name} {{",
    ]
    types = {"string": "String", "int": "Int", "long": "Long", "double": "Double"}
    members = set()
    for message in messages:
        member = kotlin_name(message.key)
        if member in members:
            fail(message.key, f"Kotlin member collision in {object_name}")
        members.add(member)
        value = message.base
        signature = value.arguments if isinstance(value, Plural) else value.format.arguments
        if not signature:
            lines.append(f"    val {member}: Int get() = R.string.{message.name}")
            continue
        tokens = value.tokens if isinstance(value, Text) else ()
        names = {p: tokens[p - 1] if tokens else f"arg{p}" for p, _ in signature}
        params = ", ".join(f"{names[p]}: {types[k]}" for p, k in signature)
        args = ", ".join(names[p] for p, _ in signature)
        if isinstance(value, Plural):
            expression = f"L10nFormatting.plural(resources, R.plurals.{message.name}, {names[value.quantity]}.toLong(), {args})"
        else:
            expression = f"L10nFormatting.string(resources, R.string.{message.name}, {args})"
        lines.extend([
            f"    fun {member}(resources: Resources, {params}): String =",
            f"        {expression}",
        ])
    lines.append("}")
    return KOTLIN + f"/{object_name}.kt", ("\n".join(lines) + "\n").encode()


def json_bytes(value) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode()


def generate(root: Path = REPOSITORY) -> tuple[dict[str, bytes], dict]:
    inputs, provenance = pinned_inputs(root)
    adaptations = load_format_adaptations(root)
    messages, input_counts = load_messages(inputs, adaptations)
    removed = exclusions(root, messages)
    included = [m for m in messages if (m.domain, m.table, m.key) not in removed]
    outputs = {}
    for locale, config in LOCALES.items():
        directory = MODULE + "/src/main/res/" + config["directory"]
        for plural in (False, True):
            outputs[directory + f"/l10n_{'plurals' if plural else 'strings'}.xml"] = resource_xml(included, locale, plural)
        if locale != "en":
            aliases = [XML_HEADER.rstrip(), f"<!-- {NOTICE} -->", "<resources>"]
            for alias, source in SCAFFOLD_TABS.items():
                message = next(m for m in included if (m.domain, m.table, m.key) == ("app", "Localizable", source))
                aliases.append(f'    <string name="{alias}" formatted="false">@string/{message.name}</string>')
            aliases.append("</resources>")
            data = ("\n".join(aliases) + "\n").encode()
            validate_resource_xml(data, f"{locale}/scaffold tab aliases")
            outputs[directory + "/l10n_scaffold_tabs.xml"] = data
    for domain, table in sorted({(m.domain, m.table) for m in included}):
        path, data = kotlin_table([m for m in included if (m.domain, m.table) == (domain, table)], domain, table)
        outputs[path] = data
    subdivisions = [m for m in included if m.domain == "app" and m.table == "Settings" and m.key.startswith("region.subdivision.")]
    if len(subdivisions) != 59 or any(m.plurals or m.base.format.arguments or set(m.strings) != set(LOCALES) for m in subdivisions):
        fail("RegionalSubdivisionLocalizationTests", "expected 59 fully localized, nonformatted subdivision keys")
    lines = [
        f"// {NOTICE}",
        f"// PortedFrom: MC1Services/Sources/MC1Services/Services/RegionalAreas.swift@{REFERENCE}",
        "package com.meshcoreone.android.core.l10n.generated",
        "",
        "import android.content.res.Resources",
        "import com.meshcoreone.android.core.l10n.R",
        "",
        "object RegionalSubdivisionNames {",
        "    private val keys = mapOf(",
    ]
    lines += [f'        "{m.key.removeprefix("region.subdivision.")}" to R.string.{m.name},' for m in subdivisions]
    lines += [
        "    )",
        "    val codes: Set<String> get() = keys.keys.toSet()",
        "    fun displayName(resources: Resources, code: String): String? =",
        "        keys[code]?.let(resources::getString)",
        "}",
    ]
    outputs[KOTLIN + "/RegionalSubdivisionNames.kt"] = ("\n".join(lines) + "\n").encode()
    locale_xml = XML_HEADER + f"<!-- {NOTICE} -->\n" + '<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n'
    locale_xml += "".join(f'    <locale android:name="{config["tag"]}" />\n' for config in LOCALES.values())
    outputs[MODULE + "/src/main/res/xml/l10n_locales.xml"] = (locale_xml + "</locale-config>\n").encode()
    outputs[MODULE + "/src/main/res/resources.properties"] = (f"# {NOTICE}\nunqualifiedResLocale=en\n").encode()

    entries = []
    input_indexes = {source["path"]: index for index, source in enumerate(provenance)}
    oracle = {"source_pin": REFERENCE, "locales": {}}
    locale_counts = {}
    for locale in LOCALES:
        oracle["locales"][locale] = []
        locale_counts[locale] = {"translated_strings": 0, "translated_plurals": 0, "english_fallback_keys": [], "identical_to_english": 0}
    for message in included:
        value = message.base
        signature = value.arguments if isinstance(value, Plural) else value.format.arguments
        entry = {
            "domain": message.domain, "table": message.table, "key": message.key,
            "android_name": message.name, "kind": "plurals" if isinstance(value, Plural) else "string",
            "arguments": [{"position": p, "type": kind} for p, kind in signature],
            "quantity_argument": value.quantity if isinstance(value, Plural) else None,
            "named_arguments": list(value.tokens) if isinstance(value, Text) else [],
            "locales": {},
        }
        for locale in LOCALES:
            effective = message.effective(locale)
            translated = locale in (message.plurals if isinstance(value, Plural) else message.strings)
            raw = effective.raw
            locale_record = {"source_input": input_indexes[effective.path]}
            if not translated:
                locale_record["english_fallback"] = True
            if isinstance(effective, Text) and effective.adaptation:
                locale_record["format_adaptation"] = effective.adaptation
            if isinstance(value, Plural):
                locale_record["quantities"] = [q for q in QUANTITIES if q in raw]
                if locale in message.strings:
                    locale_record["flat_fallback_input"] = input_indexes[message.strings[locale].path]
            entry["locales"][locale] = locale_record
            category = "translated_plurals" if isinstance(value, Plural) else "translated_strings"
            if translated:
                locale_counts[locale][category] += 1
                locale_counts[locale]["identical_to_english"] += int(raw == value.raw)
            else:
                locale_counts[locale]["english_fallback_keys"].append(message.name)
            oracle["locales"][locale].append({
                "name": message.name, "kind": entry["kind"], "raw": raw,
                "quantity_argument": entry["quantity_argument"], "arguments": entry["arguments"],
                "named_arguments": entry["named_arguments"], "source": effective.path,
                "format_adaptation": effective.adaptation if isinstance(effective, Text) else None,
            })
        entries.append(entry)
    oracle_index = {"source_pin": REFERENCE, "locales": {}}
    for locale, records in oracle["locales"].items():
        filename = f"l10n-source-{locale}.json"
        outputs[MODULE + "/src/test/resources/" + filename] = json_bytes({
            "source_pin": REFERENCE, "locale": locale, "records": records,
        })
        oracle_index["locales"][locale] = {"file": filename, "records": len(records)}
    outputs[ORACLE] = json_bytes(oracle_index)
    summary = {
        "source_pin": REFERENCE, "locales": len(LOCALES),
        "localization_inputs": sum(p["role"] == "localization" for p in provenance),
        "input_records": sum(input_counts.values()),
        "unique_source_keys": len(messages), "excluded_keys": len(removed),
        "generated_keys": len(included),
        "string_keys": sum(isinstance(m.base, Text) for m in included),
        "plural_keys": sum(isinstance(m.base, Plural) for m in included),
        "subdivision_keys": len(subdivisions),
        "source_format_adaptations": len(adaptations),
        "catalog_localized_records": sum(len(v) for v in parse_catalog(inputs[CATALOG], CATALOG).values()),
        "locale_counts": locale_counts,
        "unsupported_inputs": [],
    }
    domains = {}
    for message in included:
        domains.setdefault(message.domain, {}).setdefault(message.table, {})[message.key] = message.name
    mapping = {
        "schema_version": 1, "source_repository": "Avi0n/MeshCoreOne",
        "source_pin": REFERENCE, "source_tree": REFERENCE_TREE,
        "generator": GENERATOR,
        "generator_sha256": hashlib.sha256(host_path(root, GENERATOR).read_bytes().replace(b"\r\n", b"\n")).hexdigest(),
        "locale_map": LOCALES,
        "locale_notes": {
            "pt": "Portugal translation (TRANSLATIONS.md). Per-app choice pt-PT; values-pt retains Apple's language-wide pt fallback, including pt-BR. Runtime plural/number rules use the requested configuration locale.",
            "zh-Hans": "Explicit Simplified Chinese script qualifier values-b+zh+Hans, not generic/traditional zh.",
            "en": "Unqualified values are the complete English fallback; missing translations are omitted, never fabricated.",
        },
        "inputs": [dict(p, records=input_counts.get(p["path"])) for p in provenance],
        "locale_record_schema": {
            "source_input": "Zero-based index into inputs; exact path/blob/SHA256 are never repeated or omitted.",
            "flat_fallback_input": "Optional index of the separate strings fallback for a plural.",
            "english_fallback": "Absent means false; true is recorded only for an actual missing translation.",
            "format_adaptation": "Absent means no correction; otherwise the exact declared correction ID.",
            "quantities": "Present for plurals only, in canonical quantity order.",
        },
        "exclusion_configuration_sha256": hashlib.sha256(host_path(root, CONFIG).read_bytes().replace(b"\r\n", b"\n")).hexdigest(),
        "format_adaptation_configuration_sha256": hashlib.sha256(host_path(root, ADAPTATIONS).read_bytes().replace(b"\r\n", b"\n")).hexdigest(),
        "format_adaptations": list(adaptations.values()),
        "compatibility_aliases": {
            alias: android_name("app", "Localizable", key) for alias, key in SCAFFOLD_TABS.items()
        },
        "exclusions": [{"domain": d, "table": t, "key": k, "reason": reason} for (d, t, k), reason in sorted(removed.items())],
        "summary": summary, "domains": domains, "entries": entries,
        "android_to_source": {m.name: {"domain": m.domain, "table": m.table, "key": m.key} for m in included},
        "generated_outputs": {p: hashlib.sha256(data).hexdigest() for p, data in sorted(outputs.items())},
    }
    outputs[KEY_MAP] = json_bytes(mapping)
    summary["generated_files"] = len(outputs)
    return outputs, summary


def check_outputs(root: Path, outputs: dict[str, bytes], write: bool = False) -> None:
    expected = set(outputs)
    actual = {p.relative_to(root).as_posix() for p in host_path(root, MODULE + "/src/main/res").glob("values*/l10n_*.xml")}
    actual |= {p.relative_to(root).as_posix() for p in host_path(root, KOTLIN).glob("*.kt")}
    actual |= {p.relative_to(root).as_posix() for p in host_path(root, MODULE + "/src/test/resources").glob("l10n-source*.json")}
    actual |= {p.relative_to(root).as_posix() for p in host_path(root, MODULE + "/src/main/res/xml").glob("l10n_*.xml")}
    extras = actual - expected
    if extras:
        fail("generated outputs", f"unexpected/stale generated files: {sorted(extras)}")
    for path, data in sorted(outputs.items()):
        output = host_path(root, path)
        if write:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_bytes(data)
        current = output.read_bytes().replace(b"\r\n", b"\n") if output.is_file() else None
        if current != data:
            fail(path, "missing/modified generated output; run l10n_convert.py --write")


ANDROID_SUITES = {
    "com.meshcoreone.android.core.l10n.AirtimePercentLabelTest",
    "com.meshcoreone.android.core.l10n.RegionalSubdivisionLocalizationTest",
    "com.meshcoreone.android.core.l10n.LocalizationResourceTest",
    "com.meshcoreone.android.core.l10n.L10nFormattingTest",
}
ANDROID_CASE_MINIMUMS = {
    "com.meshcoreone.android.core.l10n.AirtimePercentLabelTest": 2,
    "com.meshcoreone.android.core.l10n.RegionalSubdivisionLocalizationTest": 3,
    "com.meshcoreone.android.core.l10n.LocalizationResourceTest": 7,
    "com.meshcoreone.android.core.l10n.L10nFormattingTest": 13,
}
ORIGINAL_CASES = {
    ("com.meshcoreone.android.core.l10n.AirtimePercentLabelTest", "airtimePercentRendersLiteralPercentSign"),
    ("com.meshcoreone.android.core.l10n.RegionalSubdivisionLocalizationTest", "everyCatalogSubdivisionKeyResolvesInEveryLocale"),
}


def check_android_tests(directory: Path, required: set[str] = ANDROID_SUITES) -> dict:
    reports = sorted(directory.glob("TEST-*.xml"))
    if not reports:
        fail(str(directory), "missing Android JUnit reports (zero tests is failure)")
    classes = set()
    discovered = 0
    identities = set()
    class_counts = {}
    for report in reports:
        try:
            suite = ET.parse(report).getroot()
        except ET.ParseError as error:
            fail(report.name, f"malformed JUnit XML: {error}")
        cases = list(suite.findall("testcase"))
        if suite.tag != "testsuite" or not cases:
            fail(report.name, "expected a nonempty testsuite")
        for field_name in ("tests", "failures", "errors", "skipped"):
            text = suite.get(field_name, "")
            if not text.isascii() or not text.isdigit():
                fail(report.name, f"missing/malformed JUnit {field_name}")
            if int(text) != (len(cases) if field_name == "tests" else 0):
                fail(report.name, f"unexpected JUnit {field_name}={text}")
        for case in cases:
            if not case.get("name") or not case.get("classname") or any(case.find(tag) is not None for tag in ("failure", "error", "skipped")):
                fail(report.name, "failed/error/skipped/malformed testcase")
            classes.add(case.attrib["classname"])
            identity = case.attrib["classname"], case.attrib["name"]
            if identity in identities:
                fail(report.name, f"duplicate testcase {identity}")
            identities.add(identity)
            class_counts[identity[0]] = class_counts.get(identity[0], 0) + 1
        discovered += len(cases)
    if classes != required:
        fail(str(directory), f"Android suite inventory mismatch: {sorted(classes ^ required)}")
    if required == ANDROID_SUITES:
        for name, minimum in ANDROID_CASE_MINIMUMS.items():
            if class_counts[name] < minimum:
                fail(str(directory), f"incomplete Android case-family discovery for {name}: {class_counts[name]} < {minimum}")
        for name, method in ORIGINAL_CASES:
            if not any(cls == name and case.startswith(method) for cls, case in identities):
                fail(str(directory), f"missing original case family {name}/{method}")
    return {
        "discovered": discovered, "passed": discovered, "failed": 0, "errors": 0, "skipped": 0,
        "suites": len(reports), "class_counts": dict(sorted(class_counts.items())),
    }


def self_test() -> int:
    sys.path.insert(0, str(host_path(REPOSITORY, "tools/android-port")))
    suite = unittest.defaultTestLoader.discover(str(host_path(REPOSITORY, "docs/android/localization")), pattern="test_*.py")
    count = suite.countTestCases()
    if count < 20:
        fail("converter self-tests", f"missing/zero/incomplete discovery: {count}")
    result = unittest.TextTestRunner(verbosity=1).run(suite)
    if not result.wasSuccessful() or result.skipped or result.testsRun != count:
        fail("converter self-tests", "failed/error/skipped/incomplete assertions")
    return count


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="Generate only declared WP-005 outputs")
    mode.add_argument("--check", action="store_true", help="Read-only drift check (the default)")
    parser.add_argument("--self-test", action="store_true", help="Require real positive/negative parser and source assertions")
    parser.add_argument("--verify-android-tests", type=Path, help="Fail closed on missing/malformed/zero/failed/skipped JUnit evidence")
    args = parser.parse_args()
    try:
        outputs, summary = generate()
        check_outputs(REPOSITORY, outputs, args.write)
        result = {k: v for k, v in summary.items() if k != "locale_counts"}
        result["english_fallback_counts"] = {locale: len(counts["english_fallback_keys"]) for locale, counts in summary["locale_counts"].items()}
        if args.self_test:
            result["python_tests"] = self_test()
        if args.verify_android_tests:
            result["android_tests"] = check_android_tests(args.verify_android_tests)
        print(json.dumps(result, indent=2, sort_keys=True))
        return 0
    except (OSError, ConversionError, UnicodeError, subprocess.SubprocessError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
