// PortedFrom: MC1Services/Sources/MC1Services/Simulator/MockDataProvider+DemoImage.swift@db14559b39d32322b06477c6ae676112f583db50
package com.meshcoreone.android.core.services.simulator

/**
 * Base64 of the embedded 120x80 gradient PNG used for the offline link-preview hero and inline image.
 * Generated, not hand-authored, and decodes to a valid 1292-byte PNG. Decoded once into
 * [MockDataProvider.demoImageData]. The line breaks mirror the Swift multi-line literal and are skipped by
 * the decoder.
 */
internal val demoImageBase64: String = listOf(
    "iVBORw0KGgoAAAANSUhEUgAAAHgAAABQCAIAAABd+SbeAAAE00lEQVR42u3Q1Y4dVBiA0f0gXHDFo0AIIYQQAiGkIaS0pVBKKW0ppUNl9Iy7u7u7u7u7u7tVaGbSyekc+78bQshO1hMsdRLwodwp8YJ4SbwiXv83qEP/j84dEcfEidgp8YJ4SbwiXsuofb+PjR0Qh8QR",
    "cUyciJ0SL4iXtqhd309M7RH7xAFxSBwRx8SJ2KllatvnUyt2xHaJPWKfOCAOiSPi2ITa9P7Mpi1im9gR2yX2iH3igDg0ota9PhfaIDaJLWKb2BHbJfaI/TNqxfOLVWKNWCc2iE1ii9gmdsTUkseXF5aJFbFVYo1YJzaITWJLQC14fHXJIrFELBMrYqvEGrFObFil5ty/",
    "NmueWCAWiSVimVgRWyXWLFAzbt9YMUvMEfPEArFILBHLxMq71JTrtxLTxIzYLDFHzBMLxCKx9JaaMFyRmySmiGliRmyWmCPmiQXDFTXq8t0bY8Q4MUFMElPENDFDzMqoYefvjY0Qo2JjxDgxQUwSU8S0LWrQ6aqpIWKYGCFGxcaIcWKCmLRM9Ttes2SAGCSGiGFihBgV",
    "GyPGzVG9jjes6yP6iQFikBgihokRYtSI6na4KdRD9Ir1Ef3EADFIDBHDZ1SH/U+dRBfRTfQQvWJ9RD8xQKi257fOtRMdRCfRRXQTPUSvWJ+Manl2+5JWsTaineggOokuopvosUo1Pb1jVjPRQrSKtRHtRAfRSXRZoBqe3LWikWgimokWolWsjWgnOkyour/v2VRPNBCN",
    "RBPRTLQQrWJtRlSN3QO5WrE6op5oIBqJJqKZaLF7oCrtHr5RRVQTNUQtUSdWTzQQjWKq/PGjCxVEJVFFVBM1RC1RJ1YvoEr/emyqTKycqCAqiSqimqghai1TxY/sLCkhSokysXKigqgkqohqc1Thn0+sKyKKiRKilCgTKycqiMp3qfyHzyQKiEKiiCgmSohSokys/C2V",
    "84d9LpEnlk8UEIVEEVFMlBAq64HjuWwih8gl8sTyiQKikCiSURn3nY1lEllENpFD5BJ5YvlEgS0q7b7BVDqRQWQSWUQ2kUPkEnkWqJR7blakEmli6UQGkUlkEdlEjgmV9LuHTclECpFKpImlExlEJpFlRCXc9RJKJJKIZCKFSCXSxNKJjDMq9jfvN+KIeLEEIpFIIpKJ",
    "FCJVTEXf8b0QQ8QScUS8WAKRSCQRyQIq8lf/S6KIaCKGiCXiiHixBCLRKhV+O9CsCCKSiCKiiRgilogj4s1RobeDrQsjwsUiiEgiiogmYojYd6ngX0IlQohQIowIF4sgIokoIvotFXgrXC6ICCZCiFAijAgXiyAib4Urv58jz/mLBRCBRBARTIQQoUSYjPL5KdqYL+FH",
    "+IsFEIFEEBFMhNiivG7GmvImfAhfwo/wFwsgAokgy5THj3GWeBJehDfhQ/gSfoS/WIA5yu1Ggk3uYh6EJ+FFeBM+hC/hZ0QZricJuRJuhLuYB+FJeBHehM8Z5XQ9xZlwIQyEK+FGuBMeYp6EcriWdsFRzIlwJlwIA+FKuBHuAur5DxmX2BMOhKOYE+FMuBAGwtUq9fRq",
    "llnPiOeEPeFAOIo5Ec6EiwXqvQ/e1/4FOlpH62hNR+toHa0LdLSO1nS0jtbRekFH62hNR+toHa0XdLSO1nS0jtbRmo7+//gHeCggAUg2kXEAAAAASUVORK5CYII=",
).joinToString("\n")
